---
language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5.3
addons:
  postgresql: '9.5'
env:
  global:
  - DATABASE_URL="postgresql://postgres:@localhost:5432/topological_inventory_sync_test?encoding=utf8&pool=5&wait_timeout=5"
before_install:
- gem install bundler
before_script:
- bundle exec rake db:create db:migrate
